include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - build/**
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - lib/l10n/*
    - lib/generated/*
    - lib/**/*.g.dart

linter:
  rules:
    public_member_api_docs: false