name: shartflix
description: "Shartflix is a movie app"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
  build_runner: ^2.4.9
  image: ^4.1.7

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/const/assets/gen/

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
