name: shartflix
description: "Shartflix is a movie app"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  formz: ^0.8.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  fresh_dio: ^0.4.3
  get_it: ^8.0.3
  go_router: ^16.0.0
  image: ^4.1.7
  image_picker: ^1.0.7
  json_annotation: ^4.9.0
  json_serializable: ^6.10.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0


flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/const/assets/gen/

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/lottie/

flutter_native_splash:
  color: "#000000"
  image: assets/images/sin_flix_splash.png
  image_dark: assets/images/sin_flix_splash.png
  color_dark: "#000000"
  android_12:
    image: assets/images/sin_flix_splash.png
    icon_background_color: "#000000"
    image_dark: assets/images/sin_flix_splash.png
    icon_background_color_dark: "#000000"
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sin_flix_logo.png"
  min_sdk_android: 21